### PR TITLE
IR sensors are analog not digital

### PR DESCRIPTION
**Pull request by wbyu2006**
Changes the command used to read the IR sensors to analogRead as necessary for the IRsensor circuitry.  The analog approach is also simpler for a student to understand because it is simply the conversion of a variable voltage to a 10-bit integer (a number from 0 to 1023) that corresponds to the voltage.  The digital approach requires circuitry with a capacitor and requires writing code to capture how long it takes the capacitor to switch from high to low voltage.

### CODE REVIEW

**Comment by blister** [comment]
What caused this? A hardware change? This is a significant deviation that requires changes to the wording in the book as well, along with the other chapters that use the IR sensors.

**Comment by blister** [comment]
Specifically at https://github.com/SumoRobotLeague/MRK-1/blob/master/Chapter_6/LineFollowingRobot.ino#L51 in lines 51/52.

**Comment by wbyu2006** [comment]
Groan....  Relax.   Nothing has changed.   My long commit explanation is just a re-statement of why we've gone with analogRead() for the IR sensors.  Your competition code merely had a typo, a slip of the tongue, or more correctly fingers.  You've got it right in that link https://github.com/SumoRobotLeague/MRK-1/blob/master/Chapter_6/LineFollowingRobot.ino#L51  
   "int leftReading = analogRead(leftSensor);" 

I'm just glad I happened to open up your code and see the error.  

The Pololu Zumo used digital ir sensors, we've only had a hand-built prototype from Kevin that used the digital circuitry for ir sensors.   

Hoping that everything else is alright.

**Comment by blister** [comment]
Interesting. I think the robot I have is the hand-built one that Kevin gave us.

**Comment by wbyu2006** [comment]
Hmm.  I doubt it.  Is the board purple?  His hand-built boards are purple.

**Comment by blister** [comment]
It's red. I think it's Rev 2. But he had to re-jigger a bunch of things to get it working.

**Comment by wbyu2006** [comment]
It'll be setup for analogRead() then.  When you've got a minute you could
upload the code and double check.

On Sat, Nov 5, 2016 at 4:20 PM, Eric Ryan Harrison <notifications@github.com

**Pull request merged**
